exclude:
  - README.md
  - LICENSE
include: ["_pages"]
remote_theme: mmistakes/minimal-mistakes@4.28.0
title: "黑青菜"
permalink : pretty
markdown: kramdown
locale: "zh-CN"
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-feed
author:
  name: "黑青菜"
  avatar: "https://cdn.jsdelivr.net/gh/hqc8848/assets@main/avatar.webp"
  bio: "业余IT人，略懂C++/Python，中度使用命令行"
  location: "江苏苏州"
  links:
    - label: "2084751346@qq.com"
      icon: "fa-fw fa-solid fa-envelope"
      url: "mailto:2084751346@qq.com" 
    - label: "hqc8848awa"
      icon: "fa-fw fa-brands fa-weixin"
      url: "weixin://contacts/profile/hqc8848awa"
    - label: "2084751346"
      icon: "fa-fw fa-brands fa-qq"
      url: "mqq://card/show_pslcard?version=1&src_type=internal&source=sharedcard&card_type=person&uin=2084751346"
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
footer:
  links:
    - label: "2084751346@qq.com"
      icon: "fa-fw fa-solid fa-envelope icon-email"
      url: "mailto:2084751346@qq.com" 
    - label: "hqc8848awa"
      icon: "fa-fw fa-brands fa-weixin icon-weixin"
      url: "weixin://contacts/profile/hqc8848awa"
    - label: "2084751346"
      icon: "fa-fw fa-brands fa-qq icon-qq"
      url: "mqq://card/show_pslcard?version=1&src_type=internal&source=sharedcard&card_type=person&uin=2084751346"
kramdown:
  math_engine: katex
